"""Synthetic IQ signal generator.

Deterministic (seedable), pure-Python baseband IQ generators so tests and demos
need no external capture files. Provides low-level primitives (tones, chirps,
bursts, noise) and higher-level *scenario* builders that emit a :class:`Capture`
together with the emitter class it is meant to represent.

These are analysis fixtures only -- baseband complex samples in memory. There is
no transmit path, no hardware access, and no modulation of real payload data.
"""

from __future__ import annotations

import math
import random
from typing import List, Sequence, Tuple

from .capture import Capture

Complex = complex
TWO_PI = 2.0 * math.pi


# --------------------------------------------------------------------------- #
# Primitives
# --------------------------------------------------------------------------- #
def complex_noise(n: int, power: float = 1.0, rng: random.Random | None = None) -> List[Complex]:
    """Circularly-symmetric complex Gaussian noise with given total power."""
    rng = rng or random.Random(0)
    sigma = math.sqrt(power / 2.0) if power > 0 else 0.0
    return [complex(rng.gauss(0.0, sigma), rng.gauss(0.0, sigma)) for _ in range(n)]


def tone(n: int, freq: float, fs: float, amp: float = 1.0, phase: float = 0.0) -> List[Complex]:
    """Complex exponential tone ``amp * exp(j(2*pi*freq/fs * k + phase))``."""
    if fs <= 0:
        fs = 1.0
    w = TWO_PI * freq / fs
    return [amp * complex(math.cos(w * k + phase), math.sin(w * k + phase)) for k in range(n)]


def chirp(n: int, f0: float, f1: float, fs: float, amp: float = 1.0) -> List[Complex]:
    """Linear frequency sweep from ``f0`` to ``f1`` over ``n`` samples."""
    if fs <= 0:
        fs = 1.0
    if n <= 1:
        return tone(n, f0, fs, amp)
    out: List[Complex] = []
    for k in range(n):
        frac = k / (n - 1)
        inst = f0 + (f1 - f0) * frac
        # integrate instantaneous frequency for phase continuity
        ph = TWO_PI * (f0 * k + 0.5 * (f1 - f0) * k * k / (n - 1)) / fs
        out.append(amp * complex(math.cos(ph), math.sin(ph)))
    return out


def wideband_burst(n: int, bandwidth: float, fs: float, amp: float = 1.0,
                   rng: random.Random | None = None) -> List[Complex]:
    """A wideband, OFDM-like burst: band-limited noise via summed random tones."""
    rng = rng or random.Random(0)
    if fs <= 0:
        fs = 1.0
    n_carriers = 128
    half_bw = min(bandwidth, fs) / 2.0
    freqs = [rng.uniform(-half_bw, half_bw) for _ in range(n_carriers)]
    phases = [rng.uniform(0, TWO_PI) for _ in range(n_carriers)]
    out: List[Complex] = []
    scale = amp / math.sqrt(n_carriers)
    for k in range(n):
        acc = 0j
        for c in range(n_carriers):
            w = TWO_PI * freqs[c] / fs
            acc += complex(math.cos(w * k + phases[c]), math.sin(w * k + phases[c]))
        out.append(scale * acc)
    return out


def spread_spectrum(n: int, bandwidth: float, fs: float, amp: float = 1.0,
                    rng: random.Random | None = None) -> List[Complex]:
    """Noise-like spread-spectrum signal band-limited to ``bandwidth`` (for GNSS-like
    fixtures). Generated by filtering complex noise with a simple moving-average
    low-pass then modulating -- resulting in a wide, noise-like hump."""
    rng = rng or random.Random(0)
    if fs <= 0:
        fs = 1.0
    base = complex_noise(n + 8, 1.0, rng)
    # crude low-pass (moving average) to shape bandwidth
    taps = max(1, int(round(fs / max(bandwidth, 1.0))))
    taps = min(taps, 8)
    filt: List[Complex] = []
    for k in range(n):
        acc = 0j
        for t in range(taps):
            acc += base[k + t]
        filt.append(acc / taps)
    # normalize to unit power then scale
    p = math.fsum((v.real * v.real + v.imag * v.imag) for v in filt) / max(1, len(filt))
    norm = amp / math.sqrt(p) if p > 0 else 0.0
    return [v * norm for v in filt]


def apply_burst_envelope(sig: List[Complex], start: int, stop: int) -> List[Complex]:
    """Zero everything outside ``[start, stop)`` (rectangular gating)."""
    out = list(sig)
    for i in range(len(out)):
        if i < start or i >= stop:
            out[i] = 0j
    return out


# --------------------------------------------------------------------------- #
# Scenario builders  ->  (Capture, expected_label)
# --------------------------------------------------------------------------- #
def _mix(dst: List[Complex], src: Sequence[Complex]) -> None:
    for i in range(min(len(dst), len(src))):
        dst[i] += src[i]


def gen_noise_only(fs: float = 2_400_000.0, duration: float = 0.02,
                   seed: int = 1, noise_power: float = 1.0) -> Tuple[Capture, str]:
    """Pure thermal noise -- no emitter present."""
    rng = random.Random(seed)
    n = int(fs * duration)
    samples = complex_noise(n, noise_power, rng)
    cap = Capture(samples=samples, sample_rate=fs, center_freq=0.0,
                  source="synthetic:noise", metadata={"scenario": "noise"})
    return cap, "none"


def gen_tone(fs: float = 2_400_000.0, duration: float = 0.02, freq: float = 300_000.0,
             snr_db: float = 30.0, seed: int = 2) -> Tuple[Capture, str]:
    """A single continuous CW carrier -> classified as ``unknown`` (bare carrier)."""
    rng = random.Random(seed)
    n = int(fs * duration)
    noise = complex_noise(n, 1.0, rng)
    amp = math.sqrt(2.0 * 10 ** (snr_db / 10.0))
    sig = tone(n, freq, fs, amp=amp)
    samples = [sig[i] + noise[i] for i in range(n)]
    cap = Capture(samples=samples, sample_rate=fs, center_freq=0.0,
                  source="synthetic:tone", metadata={"scenario": "tone"})
    return cap, "unknown"


def gen_wifi(fs: float = 20_000_000.0, duration: float = 0.01, snr_db: float = 25.0,
             seed: int = 3, position: Tuple[float, float] | None = None) -> Tuple[Capture, str]:
    """Wideband, bursty OFDM-like emissions -> ``wifi``."""
    rng = random.Random(seed)
    n = int(fs * duration)
    noise = complex_noise(n, 1.0, rng)
    samples = list(noise)
    amp = math.sqrt(2.0 * 10 ** (snr_db / 10.0)) * 4.0
    bw = 0.6 * fs
    # a few wideband bursts occupying ~40% of time
    burst_len = int(0.12 * n)
    starts = [int(0.05 * n), int(0.45 * n), int(0.75 * n)]
    for s in starts:
        b = wideband_burst(burst_len, bw, fs, amp=amp, rng=rng)
        for i in range(burst_len):
            if s + i < n:
                samples[s + i] += b[i]
    cap = Capture(samples=samples, sample_rate=fs, center_freq=2_437_000_000.0,
                  position=position, source="synthetic:wifi",
                  metadata={"scenario": "wifi"})
    return cap, "wifi"


def gen_drone_link(fs: float = 2_400_000.0, duration: float = 0.04, snr_db: float = 28.0,
                   seed: int = 4, n_channels: int = 6,
                   position: Tuple[float, float] | None = None) -> Tuple[Capture, str]:
    """Frequency-hopping narrowband control link, ms-scale dwell -> ``drone-link``."""
    rng = random.Random(seed)
    n = int(fs * duration)
    noise = complex_noise(n, 1.0, rng)
    samples = list(noise)
    amp = math.sqrt(2.0 * 10 ** (snr_db / 10.0))
    # hop channels spread across the band
    channels = [(-0.35 + 0.14 * i) * fs for i in range(n_channels)]
    dwell = int(0.0025 * fs)  # ~2.5 ms dwell (drone-scale)
    pos = int(0.01 * n)
    ci = 0
    while pos + dwell < n:
        f = channels[ci % n_channels]
        seg = tone(dwell, f, fs, amp=amp)
        for i in range(dwell):
            samples[pos + i] += seg[i]
        pos += dwell + int(0.0008 * fs)  # small gap
        ci += 1
    cap = Capture(samples=samples, sample_rate=fs, center_freq=2_440_000_000.0,
                  position=position, source="synthetic:drone",
                  metadata={"scenario": "drone-link"})
    return cap, "drone-link"


def gen_ble(fs: float = 2_400_000.0, duration: float = 0.04, snr_db: float = 26.0,
            seed: int = 5, n_channels: int = 6,
            position: Tuple[float, float] | None = None) -> Tuple[Capture, str]:
    """Very short narrowband hopping bursts (tens of us) -> ``ble``."""
    rng = random.Random(seed)
    n = int(fs * duration)
    noise = complex_noise(n, 1.0, rng)
    samples = list(noise)
    amp = math.sqrt(2.0 * 10 ** (snr_db / 10.0))
    channels = [(-0.35 + 0.14 * i) * fs for i in range(n_channels)]
    burst = int(0.00008 * fs)  # ~80 us short packet (BLE-scale)
    period = int(0.004 * fs)   # advertise every ~4 ms
    ci = 0
    pos = int(0.005 * fs)
    while pos + burst < n:
        f = channels[ci % n_channels]
        seg = tone(burst, f, fs, amp=amp)
        for i in range(burst):
            samples[pos + i] += seg[i]
        pos += period
        ci += 1
    cap = Capture(samples=samples, sample_rate=fs, center_freq=2_402_000_000.0,
                  position=position, source="synthetic:ble",
                  metadata={"scenario": "ble"})
    return cap, "ble"


def gen_gnss(fs: float = 4_000_000.0, duration: float = 0.02, snr_db: float = 10.0,
             seed: int = 6, position: Tuple[float, float] | None = None) -> Tuple[Capture, str]:
    """Continuous wideband, noise-like spread-spectrum hump -> ``gnss``.

    Moderate SNR and noise-like (high phase jitter), occupying most of the band
    continuously -- the energy-detectable footprint of a GNSS-band signal."""
    rng = random.Random(seed)
    n = int(fs * duration)
    noise = complex_noise(n, 1.0, rng)
    amp = math.sqrt(10 ** (snr_db / 10.0)) * 0.5
    bw = 0.6 * fs
    ss = wideband_burst(n, bw, fs, amp=amp, rng=rng)
    samples = [noise[i] + ss[i] for i in range(n)]
    cap = Capture(samples=samples, sample_rate=fs, center_freq=1_575_420_000.0,
                  position=position, source="synthetic:gnss",
                  metadata={"scenario": "gnss"})
    return cap, "gnss"


def gen_sweep_jammer(fs: float = 2_400_000.0, duration: float = 0.02, snr_db: float = 30.0,
                     seed: int = 7) -> Tuple[Capture, str]:
    """A fast frequency sweep across the band -- a *sweep-jamming signature* used
    only for detection/flagging. Not a transmitter; a fixture for the interference
    detector."""
    rng = random.Random(seed)
    n = int(fs * duration)
    noise = complex_noise(n, 1.0, rng)
    amp = math.sqrt(2.0 * 10 ** (snr_db / 10.0))
    sweeps: List[Complex] = []
    sweep_len = int(0.002 * fs)
    while len(sweeps) < n:
        sweeps.extend(chirp(sweep_len, -0.45 * fs, 0.45 * fs, fs, amp=amp))
    sig = sweeps[:n]
    samples = [sig[i] + noise[i] for i in range(n)]
    cap = Capture(samples=samples, sample_rate=fs, center_freq=0.0,
                  source="synthetic:sweep", metadata={"scenario": "sweep-jam"})
    return cap, "interference"


def gen_barrage_jammer(fs: float = 2_400_000.0, duration: float = 0.02, snr_db: float = 26.0,
                       seed: int = 8) -> Tuple[Capture, str]:
    """Broadband high-power noise filling most of the band -- a *barrage-jamming
    signature* for detection/flagging only (band-limited so it stands above the
    thermal floor at the band edges)."""
    rng = random.Random(seed)
    n = int(fs * duration)
    noise = complex_noise(n, 1.0, rng)
    amp = math.sqrt(10 ** (snr_db / 10.0)) * 6.0
    bw = 0.7 * fs
    jam = wideband_burst(n, bw, fs, amp=amp, rng=rng)
    samples = [noise[i] + jam[i] for i in range(n)]
    cap = Capture(samples=samples, sample_rate=fs, center_freq=0.0,
                  source="synthetic:barrage", metadata={"scenario": "barrage-jam"})
    return cap, "interference"


SCENARIOS = {
    "noise": gen_noise_only,
    "tone": gen_tone,
    "wifi": gen_wifi,
    "drone-link": gen_drone_link,
    "ble": gen_ble,
    "gnss": gen_gnss,
    "sweep": gen_sweep_jammer,
    "barrage": gen_barrage_jammer,
}


def generate(scenario: str, **kwargs) -> Tuple[Capture, str]:
    """Build a named scenario capture. See :data:`SCENARIOS`."""
    key = scenario.lower().strip()
    if key not in SCENARIOS:
        raise ValueError(f"unknown scenario: {scenario!r}")
    return SCENARIOS[key](**kwargs)
